db.url=jdbc:mysql://localhost:3306/gelatos_hibernate
db.username=root
db.password=123456


#como usar:

Ajustar classe Database

Properties props = new Properties();
InputStream input = getClass().getClassLoader().getResourceAsStream("db.properties");
props.load(input);

String url = props.getProperty("db.url");
String username = props.getProperty("db.username");
String password = props.getProperty("db.password");

connection = DriverManager.getConnection(url, username, password);
